### ISSUE TITLE
ofi_monitor_cleanup: Assertion error

### ISSUE THREAD

**Issue by kwaters4** [pnnl/lamellar-runtime#11]
When running a lamellar program in parallel there is an error when the program attempts to finish. 
I believe it is somewhere between ROFI and libfabric, if you want to this in the ROFI repo, feel free to say that and close this.

The example rust program is running to completion and then the following error occurs:

<code> test_app: prov/util/src/util_mem_monitor.c:84: ofi_monitor_cleanup: Assertion `dlist_empty(&monitor->list)' failed. </code>

libfabric version : 1.15.0

I can provide more details, just let me know.

**Comment by rdfriese** [comment]
I think you are right that this might make more sense to move to the ROFI repo, I'll close this issue her, thanks!
