### ISSUE TITLE
Implement for_each_concurrent on async branch

### ISSUE THREAD

**Issue by JosephCottam** [pnnl/lamellar-runtime#13]
Randperm uses `for_each` to "throw darts".  The[ rust documentation ](https://rust-lang.github.io/async-book/05_streams/02_iteration_and_concurrency.html) indicates that `for_each_concurrent` is the preferred equivalent.

**Comment by rdfriese** [comment]
Ahh this may be a mismatch between the way I named something and the way the language did.
we have for_each_async() implemented for distributed iterators, a quick example would be something like:
`let handle = array
        .dist_iter()
        .enumerate()
        .for_each_async(move |i,e| {
            call_async_fn(i,e); //this can also just be async block
        });
array.block_on(handle); //we can block_on the handle to wait until the iteration is completed, "array.wait_all()" could also be appropriate here
array.barrier(); //wait for all pes to finish.
`

A runnable example is shown in https://github.com/pnnl/lamellar-runtime/blob/d1a32b675734fa6d1f13f670015f5f87b2ca5ff3/examples/array_examples/array_iteration.rs#L117

If this is what you had in mind, we can either simply document it better or change the name!

**Comment by JosephCottam** [comment]
Ah!  Thanks.  That is the thing I was looking for.  Given the documentation on async uses for_each_concurrent, I would _suggest_ following that convention.  But it is also fine as it is.
