### ISSUE TITLE
Incomplete iterator function in ```array/atomic/iteration.rs```

### ISSUE THREAD

**Issue by kwaters4** [pnnl/lamellar-runtime#23]
In [the following](https://github.com/pnnl/lamellar-runtime/blob/master/src/array/atomic/iteration.rs#LL100C17-L100C17) as well [with](https://github.com/pnnl/lamellar-runtime/blob/83e65e7a796b18e82759279831ef4886b322d646/src/array/atomic/iteration.rs#LL139C11-L139C11). Is this an incomplete iterator function? It is not clear to me what they are supposed to do, return the number of elements? They appear like they are not used just yet in the examples yet.

```
 fn elems(&self, in_elems: usize) -> usize {
        in_elems
```

Thanks!

**Comment by rdfriese** [comment]
This is a case of a poorly named variable, which should actually be named something like `max_elems`. (and probably not enough documentation: [elems](https://github.com/pnnl/lamellar-runtime/blob/83e65e7a796b18e82759279831ef4886b322d646/src/array/iterator/distributed_iterator.rs#L320)

For some iterators like `map` and `enumerate` its simply enough to just pass through this value as they are not doing anything that changes the max possible elements returned by the iterator,

Some iterators though, like "[chunks](https://github.com/pnnl/lamellar-runtime/blob/83e65e7a796b18e82759279831ef4886b322d646/src/array/iterator/distributed_iterator/chunks.rs#LL60C17-L60C17), [skip](https://github.com/pnnl/lamellar-runtime/blob/83e65e7a796b18e82759279831ef4886b322d646/src/array/iterator/distributed_iterator/skip.rs#L74 ), [step_by](https://github.com/pnnl/lamellar-runtime/blob/83e65e7a796b18e82759279831ef4886b322d646/src/array/iterator/distributed_iterator/step_by.rs#L80), etc." end up modifying `max_elems` as we can concretely calculate a new lower bound for the number of elements returned.

As a note, although `filter` likely will reduce the number of elements returned, there is no way to reason about a new lower bound so it does not modify  `max_elems`.

The reason we do something like this is the help with load balancing of the final returned elements from the iteration chain, to try and prevent situations where one thread for example would only have elements that are actually "skipped" while the other threads actually have to do work.

**Comment by kwaters4** [comment]
Thanks for the explanation!
