### ISSUE TITLE
Implement Sum on LocalIterator (and LocalIterator::map)

### ISSUE THREAD

**Issue by JosephCottam** [pnnl/lamellar-runtime#26]
To enable local summarization on iterators without an intermediate array (local) allocation, implement [std::iter::sum](https://doc.rust-lang.org/std/iter/trait.Sum.html) on [LocalIterator](https://github.com/pnnl/lamellar-runtime/blob/master/src/array/iterator/local_iterator.rs) and [LocalIterator::map](https://github.com/pnnl/lamellar-runtime/blob/master/src/array/iterator/local_iterator/map.rs).

For LocalIterator...
Currently: `array.local_iter().array().sum()`
Would become: `array.local_iter().sum()`

For LocalIteror::map...
Currently: `array.local_iter().map(|e| if e > 5 {0} else {e}).array().sum()`
Would become: `array.local_iter().map(|e| if e > 5 {0} else {e}).sum()`

**Comment by rdfriese** [comment]
I have an initial implementation of "reduce" implemented for local iterators in the branch for this issue.

I'll eventually implement convenience fns like sum, prod.

In the meantime, an example for calculating "sum" would be something like

```rust
   // create an AtomicArray (for this example)
    let req = array
        .local_iter()
        .map(|elem| elem.load())
        .reduce( |acc, elem| acc + elem );

    let sum = array.block_on(req);
    println!("PE {my_pe} reduce sum: {:?}", sum);
```

**Comment by rdfriese** [comment]
continued in #29
