### ISSUE TITLE
Add API call to get number of PE threads

### ISSUE THREAD

**Issue by JosephCottam** [pnnl/lamellar-runtime#28]
I'm working on some code that will only work if the PE only has one thread to execute with (some values are not Send).  I would like to check that it was started with only one thread per PE when validating the program flags.

**Comment by rdfriese** [comment]
Ahh timely issue, there is a new function in the Dev branch for LamellarWorld called num_threads(), this will return the number of threads executing on the PE (including the main thread)

I don't currently provide the function for lamellar teams, but if you think it would be useful that's an easy thing to add!

**Comment by JosephCottam** [comment]
Does that give the threads per-pe, or total number of threads across all PEs?

On the world object would be sufficient for my needs, since I am checking the global configuration at startup.

**Comment by rdfriese** [comment]
changed this to now be `num_threads_per_pe()` instead of `num_threads()`
This function is implemented for any object that implements `LamellarEnv` #14
